server:
  port: 9091

spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://awsgoo-eureka-1:9090/eureka
