server:
  port: 9090

spring:
  application:
    name: d-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9090/eureka/
