server:
  port: 8765

spring:
  application:
    name: d-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8765/eureka/
